- name: "ensuring SMB1 server is disabled"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
    name: "SMB1"
    data: "0"
    type: dword

- name: "ensuring SMB1 client is disabled"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\services\mrxsmb10
    name: "Start"
    data: "4"
    type: dword

- name: "query 'DependOnService' list"
  win_reg_stat:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation
      name: "DependOnService"
  register: service_bag
  no_log: true

- name: "remove SMB1 dependency from SMB client"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation
    name: "DependOnService"
    data: "{{ service_bag | json_query('value[?@!=`MRxSmb10`]') }}"
    type: multistring
  when: service_bag | json_query('contains(value, `MRxSmb10`)')

- name: "uninstall SMB1 Windows Feature"
  win_optional_feature:
    name: SMB1Protocol
    state: absent
  when: ( os_ver_major.stdout | regex_replace('[\\rnt]', ''))  not in ['5.2.3790', '6.0.6001', '6.1.7601']