- name: "mitigations for AMD - CVE 2018-3639 and CVE-2017-5715"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
  loop:
    - { name: "FeatureSettingsOverride", data: "72" }
    - { name: "FeatureSettingsOverrideMask", data: "3" }
  when: proc_vendor.stdout | regex_search("AuthenticAMD")

- name: >
   "mitigations for Intel (HT enabled) - CVE-2019-11135, CVE-2018-11091, CVE-2018-12126, CVE-2018-12127, CVE-2018-12130,
   CVE-2017-5715, CVE-2017-5753, CVE-2018-3639, CVE-2017-5754, CVE-2018-3615, CVE-2018-3620, CVE-2018-3646, CVE-2018-12207"
  win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
  loop:
    - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management', name: "FeatureSettingsOverride", data: "72" }
    - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management', name: "FeatureSettingsOverrideMask", data: "3" }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization', name: "IfuErrataMitigations", data: "1"}
  when: proc_vendor.stdout | regex_search("AuthenticAMD") | ternary(false, true)

- name: "mitigations for HyperV"
  win_regedit:
    path: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization
    name: MinVmVersionForCpuBasedMitigations 
    data: "1.0"
    type: string
  when: hyperv_state.stdout | regex_search("Enabled")